name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate github-snake-dark.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Ardhaya-Johari
          outputs: |
            ./output/github-snake-dark.svg
          svg_out_path: github-snake-dark.svg
          color_snake: '#00FF00'       # bright green snake
          color_dot: '#F700FF'         # pink active dots (same as your GitHub theme)

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
